# Generated by Django 6.0.1 on 2026-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Riddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="თავსატეხი")),
                ("answer", models.CharField(max_length=200, verbose_name="პასუხი")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "მარტივი"),
                            ("medium", "საშუალო"),
                            ("hard", "რთული"),
                        ],
                        default="easy",
                        max_length=10,
                        verbose_name="სირთულე",
                    ),
                ),
                ("coins", models.IntegerField(default=10, verbose_name="კოინები")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "თავსატეხი",
                "verbose_name_plural": "თავსატეხები",
            },
        ),
    ]
