# Generated by Django 6.0.1 on 2026-01-28 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riddles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.IntegerField(default=0, verbose_name="კოინები")),
                ("level", models.IntegerField(default=1, verbose_name="დონე")),
                (
                    "is_pro",
                    models.BooleanField(default=False, verbose_name="Pro სტატუსი"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "მომხმარებლის პროფილი",
                "verbose_name_plural": "მომხმარებლების პროფილები",
            },
        ),
    ]
