# Generated by Django 6.0.1 on 2026-01-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riddles", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedRiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "riddle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="riddles.riddle"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solved_riddles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ამოხსნილი თავსატეხი",
                "verbose_name_plural": "ამოხსნილი თავსატეხები",
                "unique_together": {("user", "riddle")},
            },
        ),
    ]
