# Generated by Django 6.0.1 on 2026-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riddles", "0003_solvedriddle"),
    ]

    operations = [
        migrations.AddField(
            model_name="riddle",
            name="alternative_answers",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="ალტერნატიული პასუხები (მძიმით გამოყავით)",
            ),
        ),
        migrations.AlterField(
            model_name="riddle",
            name="answer",
            field=models.CharField(max_length=200, verbose_name="მთავარი პასუხი"),
        ),
    ]
